### ISSUE TITLE
Use Angled Margins?

### ISSUE THREAD

**Issue by colinmford** [ryanbugden/Sidebear#1]
Hey @ryanbugden,

Love this extension! But I was wondering, would you consider using the angled margin measurements?

It would require switching lines like the following to use "[angledLeftMargin](https://robofont.com/documentation/building-tools/api/fontParts/rglyph/#RGlyph.angledLeftMargin)" instead of just "leftMargin" (and same for the right) 

https://github.com/ryanbugden/Sidebear/blob/957aac703e5b319610b5cd2fe1c34287d8d12927/Sidebear.roboFontExt/lib/Sidebear.py#L192

If the user doesn't use angled margins for italics, I don't think they would notice the difference, but for those who do it would help avoid the following situation:

![image](https://user-images.githubusercontent.com/671409/75819176-2790bb80-5d68-11ea-8b03-134790f1f55e.png)

If you want me to make a PR I would be happy to do so, I just didn't know if there was a reason you were not using angled margins up til now.

**Comment by ryanbugden** [comment]
This is great, Colin, thanks! That should fix it.

**Comment by colinmford** [comment]
Great! Thanks!
